steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/davelindon-sandbox/react-router:$REVISION_ID', './react-router/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/davelindon-sandbox/react-router:latest', './react-router/']
images:
- 'gcr.io/davelindon-sandbox/react-router:$REVISION_ID'
- 'gcr.io/davelindon-sandbox/react-router:latest'

tags:
- "latest"
- "$REVISION_ID"