steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: ./react-router/
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/react-router:$REVISION_ID', '.']
  dir: ./react-router/
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/react-router:latest', '.']
  dir: ./react-router/
images:
- 'gcr.io/$PROJECT_ID/react-router:$REVISION_ID'
- 'gcr.io/$PROJECT_ID/react-router:latest'

tags:
- "latest"
- "$REVISION_ID"