apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-router
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: react-router
        version: react-router
    spec:
      containers:
      - name: frontend
        image: gcr.io/davelindon-demo/react-router:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

