apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: react-router
  annotations:
      ingress.gcp.kubernetes.io/pre-shared-cert: 'example'
spec:
  backend:
    serviceName: react-router
    servicePort: 80
