apiVersion: v1
kind: ReplicationController     
metadata:
  name: react-router
  labels:
      app: react-router
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: react-router
    spec:
      containers:
      - name: react-router
        image: gcr.io/davelindon-demo/react-router:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
