apiVersion: v1
kind: Service
metadata:
  name: react-router
  labels:
    app: react-router
spec:
  type: NodePort
  selector:
    app: react-router
  ports:
  - port: 80
    targetPort: 5000
    name: http
